name: integration-tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4.2]
        redis-version: [6]

    steps:
      - uses: actions/checkout@v2
      - name: running-test-cases
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:check-coverage
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
